owner(ticdc): fix prometheus panic
pingcap/tiflow pull request #4759
Opened 2022-03-03 08:13 UTC by overvenus

### What problem does this PR solve?

Issue Number: close #4742

### Check List 

Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
None
```

2022-03-03 08:14 UTC, overvenus commented
/check-issue-triage-complete

2022-03-03 08:18 UTC, 3AceShowHand approved these changes

2022-03-03 08:19 UTC, 3AceShowHand commented
please check the code twice to make sure no more related misbehavior in the codebase, then we can merge it.

2022-03-03 10:57 UTC, overvenus commented
/merge

2022-03-03 12:00 UTC, 3AceShowHand commented
/run-verify-ci
/run-kafka-integration-test
/run-integration-test

2022-03-03 13:35 UTC, liuzix commented
/run-leak-tests

2022-03-03 14:14 UTC, overvenus commented
/merge

2022-03-03 14:14 UTC, overvenus commented
/run-integration-test /tikv=pr/12050
/run-kafka-integration-test /tikv=pr/12050

2022-03-04 02:45 UTC, liuzix commented
/run-integration-test /tikv=pr/12050
/run-kafka-integration-test /tikv=pr/12050

2022-03-04 04:17 UTC, liuzix requested changes

2022-03-04 04:17 UTC, liuzix commented on cdc/owner/owner.go
> +					cfID, maintainTableTypeTotal).Set(float64(totalCounts[captureID]))
We need the `captureAddr` label here.

2022-03-07 02:02 UTC, liuzix approved these changes

2022-03-07 02:02 UTC, liuzix commented
/merge

2022-03-07 02:19 UTC, liuzix commented
/run-dm-compatibility-test

2022-03-07 02:35 UTC, liuzix commented
/run-kafka-integration-tests

2022-03-07 02:42 UTC, liuzix commented
/run-verify

2022-03-07 03:42 UTC, liuzix commented
/run-verify

2022-03-07 03:59 UTC, merged