cdc: reduce context switch for stateful events
pingcap/tiflow pull request #5658
Opened 2022-05-30 13:50 UTC by hicqu

Signed-off-by: qupeng <qupeng@pingcap.com>

### What problem does this PR solve?

Issue Number: close #5610 

### What is changed and how it works?

### Check List 

#### Tests 

 - No code

#### Questions 

##### Will it cause performance regression or break compatibility?

##### Do you need to update user documentation, design documentation or monitoring documentation?

### Release note 

```release-note
None
```

2022-05-30 13:51 UTC, hicqu commented
/build

2022-05-31 16:17 UTC, lonng commented on cdc/kv/client.go
> +		if isNewSubscription {
Can we use `else` directly instead of two `if` statements?

2022-05-31 16:18 UTC, lonng commented on cdc/kv/client.go
> +		isNewSubscription := !ok
Why not name the `ok` to `subscripted` to eliminate the redundant variable?

2022-06-02 06:54 UTC, hicqu commented
/run-integration-tests

2022-06-02 08:58 UTC, asddongmen commented
cdc/kv/region_worker.go:530:28: Error return value of `(github.com/pingcap/tiflow/pkg/workerpool.EventHandle).AddEvent` is not checked (errcheck)

[2022-06-02T07:15:24.648Z] 			w.handles[slot].AddEvent(ctx, &regionStatefulEvent{finishedCallbackCh: finishedCallbackCh})

2022-06-02 08:59 UTC, asddongmen requested changes
plz fix lint check, rest LGTM

2022-06-07 02:21 UTC, overvenus commented on cdc/kv/client.go
> +			err = worker.retrieveEvents(ctx, []*regionStatefulEvent{nil})
The comment and the method name conflicts. "retrieve" does not mean "send".

2022-06-07 02:21 UTC, overvenus commented on cdc/kv/client.go
> +		buffLen := len(events) / worker.inputSlots * 3 / 2
Could you add some comments about the formula?

2022-06-07 05:33 UTC, asddongmen approved these changes

2022-06-07 12:23 UTC, overvenus approved these changes
Rest LGTM

2022-06-07 13:32 UTC, hicqu commented on cdc/kv/region_worker.go
> +		return nil
No. We sub it when fetching items from the channel.

2022-06-08 05:32 UTC, lance6716 commented
/run-verify

2022-06-08 08:06 UTC, merged

2022-07-20 13:26 UTC, hicqu commented
/cherry-pick release-5.4