test(dm): inject error to a not-auto-resume source
pingcap/tiflow pull request #6624
Opened 2022-08-05 02:45 UTC by lance6716

Signed-off-by: lance6716 <lance6716@gmail.com>

### What problem does this PR solve?

Issue Number: close #6618

### What is changed and how it works?

mysql-replica-2 has turned off auto-resume, we use its worker to inject failpoint

### Check List 

#### Tests 

 - No code

#### Questions 

##### Will it cause performance regression or break compatibility?

##### Do you need to update user documentation, design documentation or monitoring documentation?

### Release note 

```release-note
`None`.
```

2022-08-05 02:45 UTC, lance6716 commented
/cc @GMHDBJD @buchuitoudegou

2022-08-08 01:52 UTC, lance6716 commented
/cc @GMHDBJD @buchuitoudegou

2022-08-08 03:16 UTC, lance6716 commented on dm/tests/shardddl2/run.sh
>  	# get worker of source1
```suggestion
	# get worker of source2
```

2022-08-08 03:32 UTC, buchuitoudegou approved these changes

2022-08-08 05:36 UTC, lance6716 commented
/cc @lichunzhu

2022-08-08 08:33 UTC, lichunzhu requested changes
LGTM

2022-08-08 08:33 UTC, lichunzhu approved these changes
LGTM

2022-08-08 08:34 UTC, lichunzhu commented
@buchuitoudegou Sorry I errorly choose `Request for change`. Could you please help approve again?

2022-08-08 08:36 UTC, lichunzhu commented
/merge

2022-08-08 08:36 UTC, lance6716 commented
/merge

2022-08-08 09:30 UTC, merged